### PR TITLE
Push 1.5.9

### PR DESCRIPTION
**Pull request by ViktorJp**
Push 1.5.9

### CODE REVIEW

**Comment by ViktorJp** [comment]
Approved

**Review by ViktorJp — COMMENTED** [review]
Approved

**Review by ViktorJp — COMMENTED** [review]
Approved

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Confirmed. I can't do anything even after my approval. I'll try again to be sure.

**Review by ExtremeFiretop — APPROVED** [review]

**Comment by ExtremeFiretop** [comment]
Nope. Still can't merge. Your safe :)

**Pull request merged**
